---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edgecdnx.edgecdnx.com
  resources:
  - prefixlists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edgecdnx.edgecdnx.com
  resources:
  - prefixlists/finalizers
  verbs:
  - update
- apiGroups:
  - edgecdnx.edgecdnx.com
  resources:
  - prefixlists/status
  verbs:
  - get
  - patch
  - update
